<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Address Book</title>
    <baes href="<?= $this->basePath() ?>/" />
</head>
<body>
    <h1>Address Book</h1>		
    <div class="container">
        <?php echo $this->content; ?>            
        <hr />
        <footer>			
            <p>Address Book &copy; 2013</p>
        </footer>
    </div>        
</body>
</html>
